apiVersion: v1
kind: Service
metadata:
  name: sdrf-editor-service
  namespace: sdrf-editor
  labels:
    app: sdrf-editor
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sdrf-editor
